version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/apps/backend-docker"
    target-branch: v3
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/apps/backend-responses"
    target-branch: v3
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/apps/backend-response-processor"
    target-branch: v3
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/apps/frontend-manage"
    target-branch: v3
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/apps/frontend-control"
    target-branch: v3
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/apps/frontend-pwa"
    target-branch: v3
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/apps/office-addin"
    target-branch: v3
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/packages/graphql"
    target-branch: v3
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/packages/prisma"
    target-branch: v3
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/packages/lti"
    target-branch: v3
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/packages/markdown"
    target-branch: v3
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/packages/grading"
    target-branch: v3
    schedule:
      interval: "weekly"
