sudo: required

language: node_js
node_js:
  - "8"

cache:
  yarn: true
  directories:
    - node_modules

services:
  - docker

script:
  - docker build . -t quay.io/uzh-bf/klicker-react:latest
  - docker login -u$QUAY_USER -p$QUAY_TOKEN quay.io/uzh-bf/klicker-react
  - docker push quay.io/uzh-bf/klicker-react:latest
