sudo: required

language: node_js
node_js:
  - "8"

cache:
  yarn: true
  directories:
    - node_modules

services:
  - docker

script:
  - yarn run build
  - ls -la
  - docker build . -t klicker-react
  - docker images
