services:
  backend:
    profiles:
      - full
    build: apps/backend-docker
    environment:
      NODE_ENV: 'development'
      DATABASE_URL: 'postgres://klicker:klicker@postgres:5432/main'
      APP_SECRET: 'abcd'
      REDIS_HOST: 'redis_exec'
      REDIS_PORT: 6379
      REDIS_CACHE_HOST: 'redis_cache'
      REDIS_CACHE_PORT: 6379
      API_DOMAIN: '127.0.0.1'
      COOKIE_DOMAIN: '127.0.0.1'
    ports:
      - 3000:3000
    networks:
      - klicker-dev

  # main database
  postgres:
    image: postgres:14.3
    environment:
      POSTGRES_USER: klicker
      POSTGRES_PASSWORD: klicker
      POSTGRES_DB: main
    ports:
      - 5432:5432
    networks:
      - klicker-dev

    # redis instance to support session execution
  redis_exec:
    image: redis:6
    ports:
      - 6379:6379
    networks:
      - klicker-dev
    volumes:
      - /data

  # redis instance for page caching and rate limiting
  redis_cache:
    image: redis:6
    ports:
      - 6380:6379
    networks:
      - klicker-dev

networks:
  klicker-dev:
    driver: bridge
