[tool.poetry]
name = "@klicker-uzh/ai-gen"
version = "0.0.1"
description = ""
authors = ["..."]
license = "AGPL-3.0"
readme = "README.md"
packages = [{include = "@klicker_uzh"}]
package-mode = false

[tool.poetry.dependencies]
python = "^3.12"
haystack-ai = "2.6.1"
haystack-experimental = "0.3.0"
fastapi = { version = "0.115.4", extras = ["standard"] }
prisma = "0.14.0"
langfuse = "2.53.9"
langfuse-haystack = "0.5.0"
python-dotenv = "1.0.1"
python-multipart = "0.0.17"
pypdf = "5.1.0"
sentence-transformers = "3.3.1"
google-ai-haystack = "^3.0.2"
anthropic-haystack = "^1.2.0"
black = "^24.10.0"
pylama = "^8.4.1"
litellm = "^1.53.5"
torch = "^2.5.1"
torchvision = "^0.20.1"
itsdangerous = "^2.2.0"
redis = "^5.2.1"
docling = "^2.10.0"

[tool.poetry.dev-dependencies]
poethepoet = "0.27.0"
ipykernel = "6.29.5"

[tool.poe.tasks]
generate = "prisma generate"
dev = "doppler run --config dev -- fastapi dev main.py"
export = "poetry export --without-hashes > requirements.txt"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
